
import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{motion}from"framer-motion";import{PiggyBank,Target,Smile,Sparkles,Plus,Minus,RotateCcw,Gift,ShieldCheck,Lock,Unlock,UserPlus,Users,CheckCircle2,ClipboardList,KeyRound,Trash2}from"lucide-react";import"./style.css";
const euro=new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"});
const newChild=(name="Mein Kind")=>({id:crypto.randomUUID?.()||Math.random().toString(16),childName:name,avatar:"🌟",fun:2,goal:3,interest:5,goalName:"Neues Spiel",goalPrice:70,tasks:[{id:"t1",title:"Zimmer aufräumen",reward:2,done:false},{id:"t2",title:"Hausaufgaben erledigen",reward:1,done:false},{id:"t3",title:"Extra helfen",reward:1.5,done:false}],history:[]});
const defaultState={pin:"1234",parentUnlocked:false,activeChildId:"demo",children:[{...newChild("Mia"),id:"demo",avatar:"🦊"}]};
function loadState(){try{const s=localStorage.getItem("taschengeld-taschen-pro");return s?JSON.parse(s):defaultState}catch{return defaultState}}function saveState(s){localStorage.setItem("taschengeld-taschen-pro",JSON.stringify(s))}
function Button({children,onClick,secondary=false,danger=false,disabled=false}){return <button disabled={disabled} onClick={onClick} className={`btn ${secondary?"secondary":""} ${danger?"danger":""}`}>{children}</button>}
function Card({children,className=""}){return <section className={`card ${className}`}>{children}</section>}
function App(){const[state,setState]=useState(loadState),[amount,setAmount]=useState(1),[pinInput,setPinInput]=useState(""),[newName,setNewName]=useState(""),[newPin,setNewPin]=useState(""),[taskTitle,setTaskTitle]=useState(""),[taskReward,setTaskReward]=useState(1);const activeChild=state.children.find(c=>c.id===state.activeChildId)||state.children[0];function update(next){setState(old=>{const v=typeof next==="function"?next(old):next;saveState(v);return v})}function updateChild(id,patcher){update(old=>({...old,children:old.children.map(c=>c.id===id?patcher(c):c)}))}function log(text){return{text,date:new Date().toLocaleDateString("de-DE"),id:crypto.randomUUID?.()||Math.random().toString(16)}}const total=useMemo(()=>activeChild.fun+activeChild.goal+activeChild.interest,[activeChild]);const goalPercent=Math.min(100,Math.round(activeChild.goal/Math.max(1,activeChild.goalPrice)*100));const monthlyInterest=Math.floor(activeChild.interest*.05*100)/100;const bonus=activeChild.interest>=100?10:activeChild.interest>=50?5:0;
function unlock(){if(pinInput===state.pin){update({...state,parentUnlocked:true});setPinInput("")}else alert("PIN stimmt nicht.")}function lock(){update({...state,parentUnlocked:false})}
function changePocket(key,delta){if(!state.parentUnlocked)return;updateChild(activeChild.id,old=>{const nextValue=Math.max(0,Math.round((old[key]+delta)*100)/100);const label=key==="fun"?"Spaß":key==="goal"?"Ziel":"Zinsen";return{...old,[key]:nextValue,history:[log(`${delta>0?"+":""}${euro.format(delta)} in ${label}`),...old.history].slice(0,30)}})}
function payday(){if(!state.parentUnlocked)return;updateChild(activeChild.id,old=>{const interest=Math.floor(old.interest*.05*100)/100;const bonus=old.interest>=100?10:old.interest>=50?5:0;return{...old,interest:Math.round((old.interest+interest+bonus)*100)/100,history:[log(`Mama-Bank: ${euro.format(interest)} Zinsen${bonus?` + ${euro.format(bonus)} Bonus`:""}`),...old.history].slice(0,30)}})}
function addChild(){if(!state.parentUnlocked||!newName.trim())return;const child=newChild(newName.trim());update(old=>({...old,children:[...old.children,child],activeChildId:child.id}));setNewName("")}
function removeChild(id){if(!state.parentUnlocked||state.children.length<=1)return;update(old=>{const children=old.children.filter(c=>c.id!==id);return{...old,children,activeChildId:children[0].id}})}
function addTask(){if(!state.parentUnlocked||!taskTitle.trim())return;updateChild(activeChild.id,old=>({...old,tasks:[...old.tasks,{id:crypto.randomUUID?.()||Math.random().toString(16),title:taskTitle.trim(),reward:Number(taskReward||0),done:false}]}));setTaskTitle("");setTaskReward(1)}
function completeTask(task){if(!state.parentUnlocked)return;updateChild(activeChild.id,old=>({...old,fun:Math.round((old.fun+Number(task.reward||0))*100)/100,tasks:old.tasks.map(t=>t.id===task.id?{...t,done:true}:t),history:[log(`Aufgabe erledigt: ${task.title} → +${euro.format(task.reward)} Spaß-Tasche`),...old.history].slice(0,30)}))}
function resetTasks(){if(!state.parentUnlocked)return;updateChild(activeChild.id,old=>({...old,tasks:old.tasks.map(t=>({...t,done:false})),history:[log("Aufgaben zurückgesetzt"),...old.history].slice(0,30)}))}
function deleteTask(id){if(!state.parentUnlocked)return;updateChild(activeChild.id,old=>({...old,tasks:old.tasks.filter(t=>t.id!==id)}))}
function resetAll(){if(!state.parentUnlocked)return;if(confirm("Wirklich alles zurücksetzen?"))update(defaultState)}function changePin(){if(!state.parentUnlocked||newPin.length<4){alert("Die neue PIN braucht mindestens 4 Zeichen.");return}update({...state,pin:newPin});setNewPin("");alert("PIN geändert.")}
const pockets=[{key:"fun",title:"Spaß-Tasche",icon:Smile,value:activeChild.fun,text:"Für Eis, Karten, Haarspangen und kleine Wünsche.",color:"pink"},{key:"goal",title:"Ziel-Tasche",icon:Target,value:activeChild.goal,text:`Sparen auf: ${activeChild.goalName}`,color:"blue"},{key:"interest",title:"5%-Zinsen-Tasche",icon:PiggyBank,value:activeChild.interest,text:"Geld wächst jeden Monat mit Mama-Bank-Zinsen.",color:"green"}];
return <main><div className="app"><motion.header initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} className="hero"><div className="hero-row"><div className="icon-box"><Sparkles/></div><div><h1>Taschengeld-Taschen PRO</h1><p>mehrere Kinder · Eltern-PIN · Aufgaben · 5%-Zinsen</p></div></div><div className="mode-box">{state.parentUnlocked?<Button onClick={lock}><Lock/> Eltern-Modus sperren</Button>:<><input className="pin-input" type="password" placeholder="Eltern-PIN" value={pinInput} onChange={e=>setPinInput(e.target.value)}/><Button onClick={unlock}><Unlock/> Entsperren</Button></>}</div><div className="status-pill">{state.parentUnlocked?"Eltern-Modus aktiv":"Kind-Modus: Geldänderungen gesperrt"}</div></motion.header>
<Card><div className="section-title"><Users/> Kind auswählen</div><div className="child-tabs">{state.children.map(child=><button key={child.id} className={child.id===activeChild.id?"child-tab active":"child-tab"} onClick={()=>update({...state,activeChildId:child.id})}><span>{child.avatar}</span> {child.childName}</button>)}</div>{state.parentUnlocked&&<div className="add-row"><input className="field" placeholder="Neues Kind" value={newName} onChange={e=>setNewName(e.target.value)}/><Button onClick={addChild}><UserPlus/> Hinzufügen</Button></div>}</Card>
<Card><input className="name-input" value={activeChild.childName} disabled={!state.parentUnlocked} onChange={e=>updateChild(activeChild.id,old=>({...old,childName:e.target.value}))}/><p className="muted">Gesamt</p><div className="total">{euro.format(total)}</div><div className="amount-row"><input type="number" min="0.5" step="0.5" value={amount} onChange={e=>setAmount(Number(e.target.value||0))} className="amount-input" disabled={!state.parentUnlocked}/><Button onClick={payday} disabled={!state.parentUnlocked}><Gift/> Monatszinsen</Button></div><p className="hint">Aktuell wären das {euro.format(monthlyInterest)} Zinsen pro Monat{bonus?` plus ${euro.format(bonus)} Bonus.`:"."}</p></Card>
{pockets.map(p=>{const Icon=p.icon;return <motion.div key={p.key} whileTap={{scale:.98}}><Card className={`pocket ${p.color}`}><div className="pocket-head"><div className="pocket-left"><div className="pocket-icon"><Icon/></div><div><h2>{p.title}</h2><p>{p.text}</p></div></div><div className="pocket-money">{euro.format(p.value)}</div></div>{p.key==="goal"&&<div className="progress-wrap"><div className="progress-label"><span>{goalPercent}% geschafft</span><span>{euro.format(activeChild.goalPrice)}</span></div><div className="progress"><div style={{width:`${goalPercent}%`}}/></div></div>}<div className="button-grid"><Button secondary disabled={!state.parentUnlocked} onClick={()=>changePocket(p.key,-amount)}><Minus/> Abziehen</Button><Button disabled={!state.parentUnlocked} onClick={()=>changePocket(p.key,amount)}><Plus/> Einzahlen</Button></div></Card></motion.div>})}
<Card><div className="section-title"><Target/> Ziel einstellen</div><input className="field" disabled={!state.parentUnlocked} value={activeChild.goalName} onChange={e=>updateChild(activeChild.id,old=>({...old,goalName:e.target.value}))}/><input type="number" className="field" disabled={!state.parentUnlocked} value={activeChild.goalPrice} onChange={e=>updateChild(activeChild.id,old=>({...old,goalPrice:Number(e.target.value||0)}))}/></Card>
<Card><div className="section-title"><ClipboardList/> Aufgaben & Belohnungen</div>{activeChild.tasks.map(task=><div key={task.id} className={task.done?"task done":"task"}><div><b>{task.done?"✅ ":""}{task.title}</b><p>{euro.format(task.reward)} Belohnung in die Spaß-Tasche</p></div><div className="task-actions"><button disabled={!state.parentUnlocked||task.done} onClick={()=>completeTask(task)}><CheckCircle2/></button><button disabled={!state.parentUnlocked} onClick={()=>deleteTask(task.id)}><Trash2/></button></div></div>)}{state.parentUnlocked&&<><div className="add-row"><input className="field" placeholder="Neue Aufgabe" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)}/><input className="field small" type="number" min="0" step="0.5" value={taskReward} onChange={e=>setTaskReward(Number(e.target.value||0))}/></div><div className="button-grid"><Button onClick={addTask}><Plus/> Aufgabe</Button><Button secondary onClick={resetTasks}><RotateCcw/> Woche neu</Button></div></>}</Card>
{state.parentUnlocked&&<Card><div className="section-title"><KeyRound/> Eltern-Einstellungen</div><input className="field" type="password" placeholder="Neue PIN" value={newPin} onChange={e=>setNewPin(e.target.value)}/><div className="button-grid"><Button onClick={changePin}>PIN ändern</Button><Button danger onClick={()=>removeChild(activeChild.id)} disabled={state.children.length<=1}><Trash2/> Kind löschen</Button></div><Button danger onClick={resetAll}><RotateCcw/> Alles zurücksetzen</Button></Card>}
<Card><div className="section-title"><ShieldCheck/> Verlauf</div>{activeChild.history.length===0?<p className="muted">Noch keine Einträge.</p>:activeChild.history.map(h=><div key={h.id} className="log"><b>{h.date}</b> – {h.text}</div>)}</Card></div></main>}
createRoot(document.getElementById("root")).render(<App/>);
